config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :outputs
  resources :pro_entries
  resources :products do
   member do      
      get "entry"
      get "output"
      
    end
    collection do
      get "electronic"
      get "home"
      get "aliments"
    end
  end

   root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	#has_many :products
	#has_many :categories_products
	#has_many :products, through: :product_categories
	has_and_belongs_to_many :products

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    var = params[:id] 
   @products = Product.joins('INNER JOIN categories_products ON products.id = categories_products.products_id').where(categories_products: {categories_id: var})
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categry.html.erb
  

 <div class="row center-xs middle-xs"> 

  <% @products.each do |product| %>
    <div class="col-md-4 col-md-offset-1 altura">
      
      <div class="row ">
          <%= image_tag product.image.url(:medium),class: "img-responsive img-rounded" %>
          <div class="col-md-10">
            <div class="row">
              <div class="col-md-6 col-md-offset-4">
                 <h3 > <%= product.name %><br></h1>
              </div> 
            </div>
            <div class="row">
              <div class="col-md-11 col-md-offset-1">
                <h5>Descripcion <%= product.description %><br></h5>
                <h5>Existencias <%= product.quantity %><br></h5>              
                <h5>Precio <%= product.cost %><br></h5>
              </div>
            </div>                        
          </div>          
      </div> 

      <div class="row">
        <div class="col-md-6 col-md-offset-3">          
          <%= link_to 'Editar', edit_product_path(product) %>
          <td><%= link_to 'Detalles', product %></td>
                                 
        </div>
      </div> 
      <div class="row"> 
        <div class="col-md-11 col-md-offset-1">  
          <%= link_to("Entrada de productos", "/products/#{product.id}/entry", class: "btn btn-success btn-sm") %>      
          <% if product.quantity > 6%>
            <% url = "/products/#{product.id}/output" %>   
            <%= link_to("Salida de productos", url,class: "btn btn-danger btn-sm") %>
            <% else %> 
              
              <%= link_to("Salida de producto", "javascript: alertProducts('/products/#{product.id}/output')", class: "btn btn-danger btn-sm" ) %>

                                     
         <%end %>          
        </div>
      </div>
      
    </div></br>
  <% end %>

 </div> <br><br>
 <%=javascript_include_tag 'products-bundle'%>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= render 'categry' %>

	

	



<%= link_to 'Edit', edit_category_path(@category) %>|
<%= link_to 'Back', categories_path %>