config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :outputs
  resources :pro_entries
  resources :products do
   member do      
      get "entry"
      get "output"
      
    end
    collection do
      get "electronic"
      get "home"
      get "aliments"
    end
  end

   root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

	validates :name, presence:{:message=>"El campo esta vacio"}
	validates :description, presence:{:message=>"El campo esta vacio"}
	validates :quantity, presence:{:message=>"El campo esta vacio"}
	validates :cost, presence:{:message=>"El campo esta vacio"}
	validates :cost, presence:{:message=>"El campo esta vacio"}
	


	after_create :save_categories

	has_attached_file :image, :styles=>{:medium=>"512*512#" , :thumb=>"100*100#", :micro=>"50*50#"}

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	#validates_attachment :image, 
		#content_type:{content_type:["image/png", "image/jpg"]}
	
	has_many :pro_entries
	has_many :outputs
	has_and_belongs_to_many :categories

	


	#custom setter
	def categories=(value)
		@categories = value
	end

	private
		# se ejecuta este metodo despues de crear el producto
		def save_categories
			@categories.each do |category_id|
				CategoriesProduct.create(categories_id: category_id, products_id: self.id)
			end
		end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :entry, :output]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    #@products = Product.where("category = '1'")
  end

  # GET /products/1
  # GET /products/1.json
  def show 
    var = params[:id]
    @inputs = ProEntry.where("products_id = #{var}")
      
    @outputs = Output.where("products_id = #{var}")
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
  end

  

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.categories = params[:categories]  

    cantidad = @product.quantity
    puts "#{cantidad}**************************************************************###}"

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/products/", notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: "/products/" }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end



 def entry
    @input = ProEntry.new
    @products = Product.all
    #cantidad = @product.quantity
    #puts "#{cantidad}**************************************************************###}"

  end

  def output
    @output = Output.new
  end

  def electronic
    @products = Product.where("category = '1'")
  end
  def aliments
    @products = Product.where("category = '2'")
  end
  def home
    @products = Product.where("category = '3'")
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category, :quantity, :cost, :image, :products_id, :quantity_input, :quantity_ouput, :categories)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_categry.html.erb
  

 <div class="row center-xs middle-xs"> 

  <% @products.each do |product| %>
    <div class="col-md-4 col-md-offset-1 altura">
      
      <div class="row ">
          <%= image_tag product.image.url(:medium),class: "img-responsive img-rounded" %>
          <div class="col-md-10">
            <div class="row">
              <div class="col-md-6 col-md-offset-4">
                 <h3 > <%= product.name %><br></h1>
              </div> 
            </div>
            <div class="row">
              <div class="col-md-11 col-md-offset-1">
                <h5>Descripcion <%= product.description %><br></h5>
                <h5>Existencias <%= product.quantity %><br></h5>              
                <h5>Precio <%= product.cost %><br></h5>
              </div>
            </div>                        
          </div>          
      </div> 

      <div class="row">
        <div class="col-md-6 col-md-offset-3">          
          <%= link_to 'Editar', edit_product_path(product) %>
          <td><%= link_to 'Detalles', product %></td>
                                 
        </div>
      </div> 
      <div class="row"> 
        <div class="col-md-11 col-md-offset-1">  
          <%= link_to("Entrada de productos", "/products/#{product.id}/entry", class: "btn btn-success btn-sm") %>      
          <% if product.quantity > 6%>
            <% url = "/products/#{product.id}/output" %>   
            <%= link_to("Salida de productos", url,class: "btn btn-danger btn-sm") %>
            <% else %> 
              
              <%= link_to("Salida de producto", "javascript: alertProducts('/products/#{product.id}/output')", class: "btn btn-danger btn-sm" ) %>

                                     
         <%end %>          
        </div>
      </div>
      
    </div></br>
  <% end %>

 </div> <br><br>
 <%=javascript_include_tag 'products-bundle'%>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-8  col-sm-8 col-xs-8 col-md-offset-2 col-xs-offset-2 col-sm-offset-2" >
      <div class="form-group">
          <div class="col-sm-10 field">
               <%= f.label "Nombre", class: " col-lg-2 control-label"%>
               <%= f.text_field :name ,class: "form-control"%>
          </div>
      </div>

      <div class="form-group">
          <div class="col-sm-10 field">
               <%= f.label "Descripcion", class: " col-lg-2 control-label"%>
               <%= f.text_field :description ,class: "form-control"%>
          </div>
      </div>

      
      <div class="form-group">
          <div class="col-sm-10 field">
               <label>Categoria</label>
               <% @categories.each do |category| %>
                <div class="field">
                  <%= check_box_tag "categories[]", category.id %> <%= category.name %>
                </div>                
               <% end %>
          </div>
      </div>

      <div class="form-group">
          <div class="col-sm-10 field">
               <%= f.label "Cantidad", class: " col-lg-2 control-label"%>
               <%= f.number_field :quantity ,class: "form-control"%>
          </div>
      </div>

      <div class="form-group">
          <div class="col-sm-10 field">
               <%= f.label "Precio", class: " col-lg-2 control-label"%>
               <%= f.text_field :cost ,class: "form-control"%>
          </div>
      </div>

      <div class="form-group">
          <div class="col-sm-10 field">
               <%= f.label "Imagen", class: " col-lg-2 control-label"%>
               <%= f.file_field :image ,class: "form-control"%>
          </div>
      </div>

       <div class="actions col-lg-8 col-md-offset-4" >
         
           <%= f.submit "Enviar", class: "btn btn-primary btn-sm" %>
            
          
        </div>
    </div>
  </div>
 
<% end %>

app/views/products/aliments.html.erb
<%= render 'categry' %>
  

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/electronic.html.erb
<%= render 'categry' %>

app/views/products/entry.html.erb
<%= form_for(@input) do |f| %>
  <% if @input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@input.errors.count, "error") %> prohibited this input from being saved:</h2>

      <ul>
      <% @input.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="row">
      <div class="col-md-6  col-sm-8 col-xs-8 col-md-offset-3 col-xs-offset-2 col-sm-offset-2 centered" >
          <div class="col-md-8 col-md-offset-2">
            <h1>Alta de productos</h1>
          </div>
          <div class="col-md-6 text-left col-md-offset-3" >
            <h2> <%= @product.name %><br></h1>
            <h3>Descripcion <%= @product.description %><br></h3>
            <h3>Existencias <%= @product.quantity %><br></h3> 
            <h3>Precio <%= @product.cost %><br></h3> 
          </div>
          <div class="form-group col-md-6 col-md-offset-3">
            <div class="col-md-12">
                
                 <%= f.number_field :quantity_input , placeholder: "Entrada de productos", class: "form-control"%>
            </div>
          </div>
          <div class="field">
            <%= f.hidden_field :products_id, :value => @product.id%>
          </div>

          <div class="actions col-md-8 col-md-offset-3" >
            <%= f.submit "Enviar productos", class: "btn btn-primary btn-sm" %>  
          </div>
      </div> 
      
    </div>  
 
<% end %>

app/views/products/home.html.erb
<%= render 'categry' %>
tabla productos
  

app/views/products/index.html.erb
<%= render 'categry' %>
  

  

app/views/products/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-4 col-xs-offset-4">
		<h1>Nuevo Producto</h1> 
	</div>
</div>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/output.html.erb
<%= form_for(@output) do |f| %>
  <% if @output.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@output.errors.count, "error") %> prohibited this output from being saved:</h2>

      <ul>
      <% @output.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-md-6  col-sm-8 col-xs-8 col-md-offset-3 col-xs-offset-2 col-sm-offset-2 centered" >
          <div class="col-md-8 col-md-offset-2">
            <h1>Baja de productos</h1>
          </div>

            

          <div class="col-md-6 text-left col-md-offset-3" >
            <h2> <%= @product.name %><br></h1>
            <h3>Descripcion <%= @product.description %><br></h3>
            <h3>Existencias <%= @product.quantity %><br></h3> 
            <h3>Precio <%= @product.cost %><br></h3> 

            
          </div>
          <div class="form-group col-md-6 col-md-offset-3">
            <div class="col-md-12">
                
                 <%= f.number_field :quantity_ouput , placeholder: "Salida de productos", class: "form-control"%>
            </div>
          </div>
          <div class="field">
            <%= f.hidden_field :products_id, :value => @product.id%>
          </div>

          <div class="actions col-md-8 col-md-offset-3" >
            <%= f.submit "Enviar", class: "btn btn-primary btn-sm" %>  
          </div>
      </div> 
      
    </div> 
  
  
<% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h3><strong>Producto:</strong> <%= @product.name %></h3>
    <h3><strong>Descripcion:</strong> <%= @product.description %><br></h3>
    <h3><strong>Existencias:</strong> <%= @product.quantity %><br></h3>              
    <h3><strong>Precio:</strong> <%= @product.cost %><br></h3>
  </div>
  <div class="col-md-6 ">
    <%= image_tag @product.image.url(:medium),class: "img-responsive img-rounded" %>
  </div>
</div> 


  
 
  



<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3><strong>Productos de entrada</strong></h3>
    <table class="table table-bordered table-hover table-striped table-responsive">
      <tr>
        <td>Fecha de entrada</td>
        <td>Cantidad de entrada</td>      
      </tr>
      <% @inputs.each do |inp| %>     
      <tr>         
        <td><%= inp.created_at %></td>
        <td><%= inp.quantity_input %></td>        
      </tr>
      <% end %>
     </table>
  </div>
</div><br>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3><strong>Productos de Salida</strong></h3>
     <table class="table table-bordered table-hover table-striped table-responsive">
      <tr>
        <td>Fecha de salida</td>
        <td>Cantidad de salida</td>
      </tr>
      <% @outputs.each do |out| %>    
      <tr>
        
        <td><%= out.created_at %></td>
        <td><%= out.quantity_ouput  %></td>
            
      </tr>
      <% end %>    
     </table>
  </div>
</div>

     


      


  
  
 

  
 
  


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>